OrdererOrgs:
  - Name: Orderer
    Domain: cardchain.com
    Specs:
      - Hostname: orderer

PeerOrgs:
  - Name: OrgA
    Domain: orga.cardchain.com
    EnableNodeOUs: true
    Template:
      Count: 2

    Users:
      Count: 2

  - Name: OrgB
    Domain: orgb.cardchain.com
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 2
